name: Build Astro Project

on:
  push:
    branches:
      - main  # O la rama que desees utilizar para el despliegue

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Revisa que esta sea la versión correcta

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Usa la versión adecuada de Node.js

      - name: Install dependencies
        run: npm install

      - name: Build Astro project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: astro-build
          path: ./dist  # Asegúrate de que esta ruta sea la correcta
